[package]
name = "linux_draft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
wasmi = "0.27.0"
wat = "1.0.60"
