[package]
name = "lwsk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
log = "0.4.17"
postcard = "1.0.4"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_toml = "0.0.1"
toml = "0.7.2"
wasmi = "0.28.0"
wat = "1.0.60"
