### Data channels
[channels]

[channels.altitude]
size = 4

[channels.speed]
size = 4


### Runables
[functions]

[functions.partition-0]
wasm = "../partition-0/target/wasm32-unknown-unknown/release/partition_0.wasm"
consumes = "altitude"
produces = "altitude"
fuel_per_call = 35000


### IO Drivers
[io]

[io.speed_in]
type = "UDP"
bind = "0.0.0.0:4000"
connect = "127.0.0.1:4001"


### Sequence of actions
[schedules]

[[schedules.01-init]]
function = "partition-0"

[[schedules.01-init]]
switch_to_schedule = "10-normal"

[[schedules.10-normal]]
function = "partition-0"

[[schedules.10-normal]]
from_channel = "altitude"
to_io = "speed_in"

[[schedules.10-normal]]
wait_ns = 1_000_000_000
